//! Sidecar runners so a compiled `.wasm` is not the thing an engineer has to
//! instantiate. `wasm-node` gets a `node foo.mjs`. `wasm-browser` gets a thin
//! `foo.html` that imports `foo.js`, which fetches `foo.wasm`.

use std::path::Path;

use crate::error::CompileError;
use crate::target::CompileTarget;

const WASM_HOST_JS: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/wasm_host.mjs"
));

pub(in crate::codegen::wasm) fn write_run_wrappers(
    wasm_path: &Path,
    target: CompileTarget,
    write_wasm_host: bool,
) -> Result<(), CompileError> {
    if write_wasm_host {
        write_wasm_host_sidecar(wasm_path)?;
    }
    match target {
        CompileTarget::WasmNode => write_node_runner(wasm_path),
        CompileTarget::WasmBrowser => {
            write_browser_module(wasm_path)?;
            write_browser_page(wasm_path)
        }
        _ => Ok(()),
    }
}

fn write_wasm_host_sidecar(wasm_path: &Path) -> Result<(), CompileError> {
    write_text(&wasm_path.with_file_name("wasm_host.mjs"), WASM_HOST_JS)
}

fn write_node_runner(wasm_path: &Path) -> Result<(), CompileError> {
    let wasm_name = file_name(wasm_path)?;
    let runner_path = wasm_path.with_extension("mjs");
    let runner_name = runner_path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("program.mjs");
    let mut source = String::new();
    source.push_str("#!/usr/bin/env node\n");
    source.push_str("// Generated by simula. Run: node ");
    source.push_str(runner_name);
    source.push_str(
        r#"
import { readFileSync } from "node:fs";
import { WASI } from "node:wasi";
import { argv, env } from "node:process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

"#,
    );
    source.push_str(WASM_HOST_JS);
    source.push_str("\nconst wasmPath = join(dirname(fileURLToPath(import.meta.url)), ");
    source.push_str(&js_string(wasm_name));
    source.push_str(
        r#");
const wasi = new WASI({
  version: "preview1",
  args: argv.slice(1),
  env,
  returnOnExit: true,
});

const bytes = readFileSync(wasmPath);
const { instance } = await instantiateSimulaWasm(
  bytes,
  { ...wasi.getImportObject() },
  {
    stdout: (text) => process.stdout.write(text),
    stderr: (text) => process.stderr.write(text),
  },
);
wasi.start(instance);
"#,
    );
    write_text(&runner_path, &source)
}

fn write_browser_module(wasm_path: &Path) -> Result<(), CompileError> {
    let wasm_name = file_name(wasm_path)?;
    let module_path = wasm_path.with_extension("js");
    let mut source = String::new();
    source.push_str("// Generated by simula. Import { run } from this module and call run().\n");
    source.push_str(WASM_HOST_JS);
    source.push_str("\nconst wasmUrl = new URL(");
    source.push_str(&js_string(wasm_name));
    source.push_str(", import.meta.url);\n");
    source.push_str(
        r#"
/**
 * Load the sibling `.wasm` and run it.
 * @param {ParentNode | { textContent: string } | null} [output]
 */
export async function run(output) {
  const outEl =
    output ??
    (typeof document !== "undefined" ? document.getElementById("out") : null);
  function write(text) {
    if (outEl) outEl.textContent += text;
  }

  const response = await fetch(wasmUrl);
  if (!response.ok) {
    throw new Error(`failed to fetch ${wasmUrl}: ${response.status}`);
  }
  const bytes = await response.arrayBuffer();
  const { instance } = await instantiateSimulaWasm(
    bytes,
    {},
    { stdout: write, stderr: write },
  );
  if (typeof instance.exports._start !== "function") {
    throw new Error("wasm-browser module missing _start export");
  }
  instance.exports._start();
  return { instance };
}
"#,
    );
    write_text(&module_path, &source)
}

fn write_browser_page(wasm_path: &Path) -> Result<(), CompileError> {
    let title = wasm_path
        .file_stem()
        .and_then(|name| name.to_str())
        .unwrap_or("sim");
    let js_name = wasm_path
        .with_extension("js")
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| CompileError::codegen("wasm output path is not a valid UTF-8 file name"))?
        .to_string();
    let page_path = wasm_path.with_extension("html");
    let mut source = String::new();
    source.push_str(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>",
    );
    source.push_str(&html_escape(title));
    source.push_str(
        r#"</title>
  <style>
    body { margin: 1rem; font: 14px/1.4 ui-monospace, SFMono-Regular, Menlo, monospace; }
    pre { white-space: pre-wrap; }
  </style>
</head>
<body>
<pre id="out"></pre>
<script type="module">
import { run } from "./"#,
    );
    source.push_str(&html_escape(&js_name));
    source.push_str(
        r#"";
await run();
</script>
</body>
</html>
"#,
    );
    write_text(&page_path, &source)
}

fn file_name(path: &Path) -> Result<&str, CompileError> {
    path.file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| CompileError::codegen("wasm output path is not a valid UTF-8 file name"))
}

fn js_string(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn write_text(path: &Path, source: &str) -> Result<(), CompileError> {
    std::fs::write(path, source).map_err(|error| {
        CompileError::codegen(format!(
            "failed to write wasm runner {}: {error}",
            path.display()
        ))
    })
}
